apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: minio-pv
      labels:
        type: local
    spec:
      storageClassName: sc-local
      capacity:
        storage: 30Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      hostPath:
        path: "/home/data/minio/data"
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: minio-pv0
      labels:
        type: local
    spec:
      storageClassName: sc-local
      capacity:
        storage: 30Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      hostPath:
        path: "/home/data/minio/data"
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: minio-pv1
      labels:
        type: local
    spec:
      storageClassName: sc-local
      capacity:
        storage: 30Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      hostPath:
        path: "/home/data/minio/data"
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: minio-pv2
      labels:
        type: local
    spec:
      storageClassName: sc-local
      capacity:
        storage: 30Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      hostPath:
        path: "/home/data/minio/data"
