apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 30005
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
  sessionAffinity: ClientIP
